framework:
  cache:

    app: cache.adapter.memcached
    default_memcached_provider: "memcached://%env(MEMCACHED_PROVIDER)%"

    pools:
      my_cache_pool:
        adapters:
          - { name: cache.adapter.memcached, provider: "memcached://%env(MEMCACHED_PROVIDER)%", tags: true }
          - { name: cache.adapter.memcached, provider: "memcached://%env(MEMCACHED_PROVIDER_2)%", tags: true }