version: '3'

services:
  web_bounces:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - .:/var/www/html
    env_file:
      - .env.local
    ports:
      - "8010:80"
    stdin_open: true
    tty: true

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
