# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $infusionsoft_clientId: "%env(INFUSIONSOFT_CLIENT_ID)%"
      $infusionsoft_clientSecret: "%env(INFUSIONSOFT_CLIENT_SECRET)%"
      $infusionsoft_redirectUri: "%env(INFUSIONSOFT_REDIRECT_URI)%"
      $update_score_time_limit: '2 days ago'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Migrations/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Service\HandleBounced\Parameter\SubscriptionCounter:
    arguments:
      $weight: 5
      $base_value: 1
      $coefficient_of_quality: 0.5
      $formula: '@App\Service\HandleBounced\ParameterFormula\UnlimitedPositive'
      $infusionsoftApi: '@App\Service\Keap\InfusionsoftApi'

  App\Service\HandleBounced\Parameter\ExClientParameter:
    arguments:
      $weight: 4
      $base_value: 1
      $coefficient_of_quality: 1
      $formula: '@App\Service\HandleBounced\ParameterFormula\DefaultPositive'
      $infusionsoftApi: '@App\Service\Keap\InfusionsoftApi'

  App\Service\HandleBounced\Parameter\BouncedCounter:
    arguments:
      $weight: 3
      $base_value: 1
      $coefficient_of_quality: 0.5
      $formula: '@App\Service\HandleBounced\ParameterFormula\UnlimitedPositive'

  App\Service\HandleBounced\Parameter\ComplaintCounter:
    arguments:
      $weight: 2
      $base_value: 1
      $coefficient_of_quality: 0.5
      $formula: '@App\Service\HandleBounced\ParameterFormula\UnlimitedPositive'

  App\Service\HandleBounced\Parameter\CompanyUserParameter:
    arguments:
      $weight: 1
      $base_value: 1
      $coefficient_of_quality: 1
      $formula: '@App\Service\HandleBounced\ParameterFormula\DefaultPositive'
      $infusionsoftApi: '@App\Service\Keap\InfusionsoftApi'

  App\Service\HandleBounced\Appraiser:
    arguments:
      $formula: '@App\Service\HandleBounced\QualityFormula\ArithmeticMeanFormula'
      $parameters: [
        '@App\Service\HandleBounced\Parameter\SubscriptionCounter',
        '@App\Service\HandleBounced\Parameter\ExClientParameter',
        '@App\Service\HandleBounced\Parameter\BouncedCounter',
        '@App\Service\HandleBounced\Parameter\ComplaintCounter',
        '@App\Service\HandleBounced\Parameter\CompanyUserParameter',
      ]